#!/usr/bin/env python3
"""
import_products.py - Read docs/products_en.xlsx and generate SQL seed data.

Uses markitdown to convert xlsx to markdown, then parses the tables to generate
INSERT statements for products and product_specs tables.
"""

import re
import json
import os
from markitdown import MarkItDown

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
XLSX_PATH = os.path.join(BASE_DIR, "docs", "products_en.xlsx")
OUTPUT_PATH = os.path.join(BASE_DIR, "supabase", "seed", "products.sql")

CATEGORY_MAP = {
    "Drones": "uav",
    "Payload": "payload",
    "C-UAS": "cuas",
    "Ground Control": "ground_control",
    "Quadruped Intelligent Robot System": "ground_control",
    "Unmanned Vehicle System": "ground_control",
}


def generate_slug(model: str) -> str:
    """Generate a URL-friendly slug from a model name."""
    slug = model.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    slug = re.sub(r"-+", "-", slug)
    return slug


def escape_sql_string(s: str) -> str:
    """Escape a string for use in SQL single-quoted literals."""
    return s.replace("'", "''")


def parse_markdown_table(lines: list[str]) -> list[dict]:
    """Parse markdown table rows into list of dicts using header names."""
    if not lines:
        return []

    # Parse header (first line)
    header_line = lines[0]
    headers = [h.strip() for h in header_line.split("|")[1:-1]]

    rows = []
    for line in lines[1:]:  # Skip header line
        if "---" in line:
            continue
        parts = [p.strip() for p in line.split("|")[1:-1]]
        if len(parts) >= len(headers):
            row = {}
            for i, h in enumerate(headers):
                row[h] = parts[i] if i < len(parts) else ""
            rows.append(row)
    return rows


def parse_product_overview_table(rows: list[dict]) -> dict[str, dict]:
    """Parse the product overview table, grouping by product name."""
    products = {}
    for row in rows:
        name = row.get("产品名称", "").strip()
        if not name or name == "---":
            continue
        category_raw = row.get("分类", "").strip()
        overview = row.get("产品概述", "").strip()
        advantages = row.get("核心优势", "").strip()
        capabilities = row.get("核心能力", "").strip()
        applications = row.get("应用场景", "").strip()

        products[name] = {
            "model": name,
            "category_raw": category_raw,
            "overview": overview,
            "advantages": advantages,
            "capabilities": capabilities,
            "applications": applications,
        }
    return products


def parse_specs_table(rows: list[dict]) -> dict[str, list[tuple[str, str]]]:
    """Parse the detailed specs table, grouping specs by product name."""
    specs = {}
    for row in rows:
        name = row.get("产品名称", "").strip()
        if not name or name == "---" or name == "产品名称":
            continue
        param_name = row.get("参数名称", "").strip()
        param_value = row.get("参数值", "").strip()
        if param_name and param_value and param_name != "参数名称":
            specs.setdefault(name, []).append((param_name, param_value))
    return specs


def generate_sql(products: dict, specs: dict) -> str:
    """Generate SQL INSERT statements for products and product_specs."""
    lines = [
        "-- seed/products.sql",
        "-- Auto-generated by import_products.py from docs/products_en.xlsx",
        "",
    ]

    # Sort products by model name for consistent ordering
    sorted_names = sorted(products.keys())

    product_lines = []
    spec_lines = []
    sort_order = 0

    for name in sorted_names:
        p = products[name]
        model = p["model"]
        slug = generate_slug(model)
        category = CATEGORY_MAP.get(p["category_raw"], "uav")

        # Determine sub_category for ground_control items
        sub_category = None
        if p["category_raw"] == "Quadruped Intelligent Robot System":
            sub_category = "quadruped"
        elif p["category_raw"] == "Unmanned Vehicle System":
            sub_category = "ugv"

        # Build translations JSON
        overview = p["overview"]
        advantages = p["advantages"]
        capabilities = p["capabilities"]
        applications = p["applications"]

        translations = {"en": {}}
        if overview:
            translations["en"]["overview"] = overview
        if advantages:
            translations["en"]["advantages"] = advantages
        if capabilities:
            translations["en"]["capabilities"] = capabilities
        if applications:
            translations["en"]["applications"] = applications

        # Featured: first 6 products
        featured = sort_order < 6

        # Build specs JSON
        product_specs_list = specs.get(name, [])
        specs_json = {}
        for label, value in product_specs_list:
            specs_json[label] = value

        # Escape for SQL
        model_escaped = escape_sql_string(model)
        slug_escaped = escape_sql_string(slug)
        translations_escaped = escape_sql_string(json.dumps(translations, ensure_ascii=False))
        specs_escaped = escape_sql_string(json.dumps(specs_json, ensure_ascii=False))
        sub_category_sql = f"'{escape_sql_string(sub_category)}'" if sub_category else "NULL"

        product_lines.append(
            f"  ('{model_escaped}', '{slug_escaped}', '{category}', {sub_category_sql}, "
            f"'{specs_escaped}'::jsonb, '{translations_escaped}'::jsonb, "
            f"'{{}}', NULL, NULL, {str(featured).lower()}, true, {sort_order})"
        )

        # Generate product_specs INSERTs
        for spec_sort, (label, value) in enumerate(product_specs_list):
            label_json = json.dumps({"en": label}, ensure_ascii=False)
            value_json = json.dumps({"en": value}, ensure_ascii=False)
            label_escaped = escape_sql_string(label_json)
            value_escaped = escape_sql_string(value_json)
            spec_lines.append(
                f"  ((SELECT id FROM products WHERE slug = '{slug_escaped}'), "
                f"'{label_escaped}'::jsonb, '{value_escaped}'::jsonb, {spec_sort})"
            )

        sort_order += 1

    # Products INSERT
    lines.append("INSERT INTO products (model, slug, category, sub_category, specs, translations, images, datasheet_url, compliance_flag, featured, published, sort_order) VALUES")
    lines.append(",\n".join(product_lines))
    lines.append(";\n")

    # Product specs INSERT
    if spec_lines:
        lines.append("INSERT INTO product_specs (product_id, label, value, sort_order) VALUES")
        lines.append(",\n".join(spec_lines))
        lines.append(";\n")

    return "\n".join(lines)


def main():
    print(f"Reading {XLSX_PATH}...")
    md = MarkItDown()
    result = md.convert(XLSX_PATH)
    content = result.text_content

    # Split into sections by "##" headers
    sections = re.split(r"^## ", content, flags=re.MULTILINE)

    overview_rows = []
    specs_rows = []

    for section in sections:
        lines = section.strip().split("\n")
        # Find table lines
        table_lines = [l for l in lines if l.strip().startswith("|")]

        if not table_lines:
            continue

        # Determine which table this is based on header
        section_title = lines[0].strip() if lines else ""

        if "产品完整信息" in section_title or "完整信息" in section_title:
            overview_rows = parse_markdown_table(table_lines)
        elif "详细参数" in section_title:
            specs_rows = parse_markdown_table(table_lines)

    if not overview_rows:
        print("ERROR: Could not find product overview table in xlsx")
        return

    products = parse_product_overview_table(overview_rows)
    print(f"Found {len(products)} products")

    specs = parse_specs_table(specs_rows) if specs_rows else {}
    print(f"Found specs for {len(specs)} products")

    sql = generate_sql(products, specs)

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Generated {OUTPUT_PATH}")
    print(f"Total products: {len(products)}")
    print(f"Total spec entries: {sum(len(v) for v in specs.values())}")


if __name__ == "__main__":
    main()
