import json
import re

# 专业术语翻译映射（按优先级排序，长的先替换）
term_translations = {
    "Vertical Take-Off and Landing": "Despegue y Aterrizaje Vertical",
    "unmanned aerial system": "sistema aéreo no tripulado",
    "unmanned aerial vehicle": "vehículo aéreo no tripulado",
    "unmanned all-terrain": "todo terreno no tripulado",
    "catapult take off": "despegue por catapulta",
    "catapult take-off": "despegue por catapulta",
    "Pneumatic Catapult Take-Off": "Despegue por Catapulta Neumática",
    "catapult launch": "lanzamiento por catapulta",
    "situational awareness": "conciencia situacional",
    "legitimate defense": "defensa legítima",
    "border security": "seguridad fronteriza",
    "humanitarian relief": "ayuda humanitaria",
    "ground station": "estación terrestre",
    "data link": "enlace de datos",
    "Data Link": "Enlace de Datos",
    "wind resistance": "resistencia al viento",
    "Wind Resistance": "Resistencia al Viento",
    "Payload Capacity": "Capacidad de Carga Útil",
    "payload capacity": "capacidad de carga útil",
    "Maximum Payload": "Carga Útil Máxima",
    "payload hardpoint": "punto duro de carga útil",
    "Payload Hardpoints": "Puntos Duros de Carga Útil",
    "payload mounting": "montaje de carga útil",
    "Payload Mounting Points": "Puntos de Montaje de Carga Útil",
    "legitimate payload": "carga útil legítima",
    "logistics payload": "carga útil logística",
    "security payload": "carga útil de seguridad",
    "lightweight payload": "carga útil ligera",
    "heavy payload": "carga útil pesada",
    "payload delivery": "entrega de carga útil",
    "Maximum Endurance": "Autonomía Máxima",
    "endurance": "autonomía",
    "Maximum Range": "Alcance Máximo",
    "long-range": "largo alcance",
    "long range": "largo alcance",
    "medium-range": "medio alcance",
    "medium range": "medio alcance",
    "short-range": "corto alcance",
    "short range": "corto alcance",
    "Maximum Ceiling": "Techo de Servicio Máximo",
    "ceiling": "techo de servicio",
    "Cruise Speed": "Velocidad de Crucero",
    "Cruising Speed": "Velocidad de Crucero",
    "cruise speed": "velocidad de crucero",
    "Maximum Speed": "Velocidad Máxima",
    "Cruise Altitude": "Altitud de Crucero",
    "Cruising Altitude": "Altitud de Crucero",
    "cruise altitude": "altitud de crucero",
    "Communication System": "Sistema de Comunicación",
    "communication system": "sistema de comunicación",
    "Satellite Communication": "Comunicación Satelital",
    "satellite communication": "comunicación satelital",
    "Control Method": "Método de Control",
    "Take-Off Method": "Método de Despegue",
    "take-off method": "método de despegue",
    "Recovery Method": "Método de Recuperación",
    "Take-Off Requirements": "Requisitos de Despegue",
    "Propulsion System": "Sistema de Propulsión",
    "propulsion system": "sistema de propulsión",
    "Electric-powered": "Eléctrico",
    "electric-powered": "eléctrico",
    "Gasoline-powered": "Gasolina",
    "gasoline-powered": "gasolina",
    "Oil-powered": "Combustible",
    "oil-powered": "combustible",
    "Multi-UAV Coordination": "Coordinación Multi-VANT",
    "Multi-UAV Collaboration": "Colaboración Multi-VANT",
    "multi-UAV": "multi-VANT",
    "Swarm Coordination": "Coordinación de Enjambre",
    "swarm coordination": "coordinación de enjambre",
    "Reconnaissance Equipment": "Equipo de Reconocimiento",
    "reconnaissance equipment": "equipo de reconocimiento",
    "reconnaissance": "reconocimiento",
    "Visual Reconnaissance": "Reconocimiento Visual",
    "Electro-optical": "Electro-óptico",
    "electro-optical": "electro-óptico",
    "HD Camera": "Cámara HD",
    "HD camera": "cámara HD",
    "Thermal Imaging": "Imagen Térmica",
    "thermal imaging": "imagen térmica",
    "Laser Ranging": "Telemetría Láser",
    "laser ranging": "telemetría láser",
    "Image Transmission": "Transmisión de Imagen",
    "image transmission": "transmisión de imagen",
    "Digital/Analog": "Digital/Analógica",
    "digital/analog": "digital/analógica",
    "Return-to-Home": "Retorno a Base",
    "return-to-home": "retorno a base",
    "Autonomous Return": "Retorno Autónomo",
    "autonomous return": "retorno autónomo",
    "Remote Return": "Retorno Remoto",
    "remote return": "retorno remoto",
    "Parachute Recovery": "Recuperación con Paracaídas",
    "parachute recovery": "recuperación con paracaídas",
    "Safety Function": "Función de Seguridad",
    "safety function": "función de seguridad",
    "Self-protection": "Autoprotección",
    "self-protection": "autoprotección",
    "Self-security": "Autoseguridad",
    "self-security": "autoseguridad",
    "Anti-jamming": "Anti-interferencia",
    "anti-jamming": "anti-interferencia",
    "Maximum Take-Off Weight": "Peso Máximo al Despegue",
    "take-off weight": "peso al despegue",
    "Dimensions": "Dimensiones",
    "Weight": "Peso",
    "Net Weight": "Peso Neto",
    "Other Features": "Otras Características",
    "Key Features": "Características Clave",
    "Key Feature": "Característica Clave",
    "Deployment Type": "Tipo de Despliegue",
    "Deployment Design": "Diseño de Despliegue",
    "Single-Mission": "Misión Única",
    "single-mission": "misión única",
    "Batched Rapid Deployment": "Despliegue Rápido por Lotes",
    "batched rapid deployment": "despliegue rápido por lotes",
    "Rapid Deployment": "Despliegue Rápido",
    "rapid deployment": "despliegue rápido",
    "Vehicle-mounted": "Montado en Vehículo",
    "vehicle-mounted": "montado en vehículo",
    "Maximum Coverage": "Cobertura Máxima",
    "maximum coverage": "cobertura máxima",
    "Navigation System": "Sistema de Navegación",
    "navigation system": "sistema de navegación",
    "GPS + Inertial Navigation": "GPS + Navegación Inercial",
    "Inertial Navigation": "Navegación Inercial",
    "inertial navigation": "navegación inercial",
    "Remote Controller": "Control Remoto",
    "remote controller": "control remoto",
    "Remote Control": "Control Remoto",
    "remote control": "control remoto",
    "Logistics & Support": "Logística y Apoyo",
    "logistics & support": "logística y apoyo",
    "Logistics Support": "Apoyo Logístico",
    "logistics support": "apoyo logístico",
    "logistics": "logística",
    "Heavy-duty": "Servicio Pesado",
    "heavy-duty": "servicio pesado",
    "Heavy-lift": "Carga Pesada",
    "heavy-lift": "carga pesada",
    "Medium-lift": "Carga Media",
    "medium-lift": "carga media",
    "Lightweight": "Ligero",
    "lightweight": "ligero",
    "Ultra-lightweight": "Ultraligero",
    "ultra-lightweight": "ultraligero",
    "Ultra-miniature": "Ultra-miniatura",
    "ultra-miniature": "ultra-miniatura",
    "High-performance": "Alto Rendimiento",
    "high-performance": "alto rendimiento",
    "High-speed": "Alta Velocidad",
    "high-speed": "alta velocidad",
    "Long-endurance": "Larga Autonomía",
    "long-endurance": "larga autonomía",
    "Ultra-long endurance": "Ultra-larga Autonomía",
    "ultra-long endurance": "ultra-larga autonomía",
    "Multi-rotor": "Multi-rotor",
    "multi-rotor": "multi-rotor",
    "Fixed-wing": "Ala Fija",
    "fixed-wing": "ala fija",
    "VTOL": "VTOL",
    "UAV": "VANT",
    "Write a Review": "Escribir una Reseña",
    "Product Overview": "Descripción del Producto",
    "Core Advantages": "Ventajas Principales",
    "Core Capabilities": "Capacidades Principales",
    "Core Security Capabilities": "Capacidades de Seguridad Principales",
    "Core Logistics Capabilities": "Capacidades Logísticas Principales",
    "Core Situational Awareness Capabilities": "Capacidades de Conciencia Situacional Principales",
    "Authorized Application Scenarios": "Escenarios de Aplicación Autorizados",
    "Legitimate National Defense": "Defensa Nacional Legítima",
    "legitimate national defense": "defensa nacional legítima",
    "Border Control": "Control Fronterizo",
    "border control": "control fronterizo",
    "Homeland Security": "Seguridad Nacional",
    "homeland security": "seguridad nacional",
    "Emergency Response": "Respuesta de Emergencia",
    "emergency response": "respuesta de emergencia",
    "Security Response": "Respuesta de Seguridad",
    "security response": "respuesta de seguridad",
    "Security Monitoring": "Monitoreo de Seguridad",
    "security monitoring": "monitoreo de seguridad",
    "Security Patrol": "Patrullaje de Seguridad",
    "security patrol": "patrullaje de seguridad",
    "Border Patrol": "Patrullaje Fronterizo",
    "border patrol": "patrullaje fronterizo",
    "Supply Delivery": "Entrega de Suministros",
    "supply delivery": "entrega de suministros",
    "Cargo Delivery": "Entrega de Carga",
    "cargo delivery": "entrega de carga",
    "Transportation": "Transporte",
    "transportation": "transporte",
    "Surveillance": "Vigilancia",
    "surveillance": "vigilancia",
    "Monitoring": "Monitoreo",
    "monitoring": "monitoreo",
    "Assessment": "Evaluación",
    "assessment": "evaluación",
    "Operations": "Operaciones",
    "operations": "operaciones",
    "Missions": "Misiones",
    "missions": "misiones",
    "Tasks": "Tareas",
    "tasks": "tareas",
    "Equipment": "Equipo",
    "equipment": "equipo",
    "Platform": "Plataforma",
    "platform": "plataforma",
    "System": "Sistema",
    "system": "sistema",
    "Capability": "Capacidad",
    "capability": "capacidad",
    "Function": "Función",
    "function": "función",
    "Design": "Diseño",
    "design": "diseño",
    "Performance": "Rendimiento",
    "performance": "rendimiento",
    "Operation": "Operación",
    "operation": "operación",
    "Deployment": "Despliegue",
    "deployment": "despliegue",
    "Response": "Respuesta",
    "response": "respuesta",
    "Support": "Apoyo",
    "support": "apoyo",
    "Capacity": "Capacidad",
    "capacity": "capacidad",
    "Level": "Nivel",
    "level": "nivel",
    "Point": "Punto",
    "point": "punto",
    "Points": "Puntos",
    "points": "puntos",
    "Rated": "Nominal",
    "rated": "nominal",
    "Total": "Total",
    "total": "total",
    "Maximum": "Máximo",
    "maximum": "máximo",
    "Minimum": "Mínimo",
    "minimum": "mínimo",
    "Continuous": "Continuo",
    "continuous": "continuo",
    "Stable": "Estable",
    "stable": "estable",
    "Reliable": "Confiable",
    "reliable": "confiable",
    "Flexible": "Flexible",
    "flexible": "flexible",
    "Integrated": "Integrado",
    "integrated": "integrado",
    "Enhanced": "Mejorado",
    "enhanced": "mejorado",
    "Optional": "Opcional",
    "optional": "opcional",
    "Supported": "Soportado",
    "supported": "soportado",
    "Authorized": "Autorizado",
    "authorized": "autorizado",
    "Legitimate": "Legítimo",
    "legitimate": "legítimo",
    "Professional": "Profesional",
    "professional": "profesional",
    "Compact": "Compacto",
    "compact": "compacto",
    "Portable": "Portátil",
    "portable": "portátil",
    "Individual": "Individual",
    "individual": "individual",
    "Personnel": "Personal",
    "personnel": "personal",
    "Agency": "Agencia",
    "agency": "agencia",
    "Agencies": "Agencias",
    "agencies": "agencias",
    "Government": "Gobierno",
    "government": "gobierno",
    "Defense": "Defensa",
    "defense": "defensa",
    "Security": "Seguridad",
    "National": "Nacional",
    "national": "nacional",
    "International": "Internacional",
    "international": "internacional",
    "Regional": "Regional",
    "regional": "regional",
    "Remote": "Remoto",
    "remote": "remoto",
    "Complex": "Complejo",
    "complex": "complejo",
    "Harsh": "Adverso",
    "harsh": "adverso",
    "Extreme": "Extremo",
    "extreme": "extremo",
    "Adverse": "Adverso",
    "adverse": "adverso",
    "Environment": "Entorno",
    "environment": "entorno",
    "Terrain": "Terreno",
    "terrain": "terreno",
    "Area": "Área",
    "area": "área",
    "Region": "Región",
    "region": "región",
    "Zone": "Zona",
    "zone": "zona",
    "Space": "Espacio",
    "space": "espacio",
    "Airspace": "Espacio Aéreo",
    "airspace": "espacio aéreo",
    "Altitude": "Altitud",
    "altitude": "altitud",
    "Height": "Altura",
    "height": "altura",
    "Length": "Longitud",
    "length": "longitud",
    "Width": "Ancho",
    "width": "ancho",
    "Wingspan": "Envergadura",
    "wingspan": "envergadura",
    "Diameter": "Diámetro",
    "diameter": "diámetro",
    "Distance": "Distancia",
    "distance": "distancia",
    "Speed": "Velocidad",
    "speed": "velocidad",
    "Time": "Tiempo",
    "time": "tiempo",
    "Hour": "Hora",
    "hour": "hora",
    "Minute": "Minuto",
    "minute": "minuto",
    "Second": "Segundo",
    "second": "segundo",
    "Power": "Potencia",
    "power": "potencia",
    "Energy": "Energía",
    "energy": "energía",
    "Electric": "Eléctrico",
    "electric": "eléctrico",
    "Gasoline": "Gasolina",
    "gasoline": "gasolina",
    "Oil": "Combustible",
    "oil": "combustible",
    "Clean": "Limpia",
    "clean": "limpia",
    "Quiet": "Silenciosa",
    "quiet": "silenciosa",
    "Low noise": "Bajo ruido",
    "low noise": "bajo ruido",
    "High efficiency": "Alta eficiencia",
    "high efficiency": "alta eficiencia",
    "High power": "Alta potencia",
    "high power": "alta potencia",
    "High torque": "Alto par motor",
    "high torque": "alto par motor",
}

# 规格键名翻译映射
spec_key_translations = {
    "Weight": "Peso",
    "Dimensions": "Dimensiones",
    "Dimensions (L×W×H)": "Dimensiones (L×W×H)",
    "Dimensions (L&times;W&times;H)": "Dimensiones (L×W×H)",
    "Maximum Take-Off Weight": "Peso Máximo al Despegue",
    "Take-Off Method": "Método de Despegue",
    "Recovery Method": "Método de Recuperación",
    "Maximum Endurance": "Autonomía Máxima",
    "Maximum Range": "Alcance Máximo",
    "Maximum Control Distance": "Distancia Máxima de Control",
    "Take-Off Requirements": "Requisitos de Despegue",
    "Cruise Speed": "Velocidad de Crucero",
    "Maximum Speed": "Velocidad Máxima",
    "Cruising Speed": "Velocidad de Crucero",
    "Cruise Altitude": "Altitud de Crucero",
    "Cruising Altitude": "Altitud de Crucero",
    "Maximum Ceiling": "Techo de Servicio Máximo",
    "Wind Resistance": "Resistencia al Viento",
    "Communication System": "Sistema de Comunicación",
    "Control Method": "Método de Control",
    "Payload Capacity": "Capacidad de Carga Útil",
    "Payload Mounting Points": "Puntos de Montaje de Carga Útil",
    "Payload Hardpoints": "Puntos Duros de Carga Útil",
    "Single Hardpoint Payload": "Carga Útil por Punto Duro",
    "Payload Capacity per Hardpoint": "Carga Útil por Punto Duro",
    "Payload Type": "Tipo de Carga Útil",
    "Maximum Payload": "Carga Útil Máxima",
    "Multi-UAV Coordination": "Coordinación Multi-VANT",
    "Multi-UAV Collaboration": "Colaboración Multi-VANT",
    "Swarm Coordination Capability": "Capacidad de Coordinación de Enjambre",
    "Recovery/Safety Function": "Función de Recuperación/Seguridad",
    "Return Function": "Función de Retorno",
    "Return/Safety Function": "Función de Retorno/Seguridad",
    "Self-protection Function": "Función de Autoprotección",
    "Self-security Function": "Función de Autoseguridad",
    "Propulsion System": "Sistema de Propulsión",
    "Other Features": "Otras Características",
    "Key Features": "Características Clave",
    "Key Feature": "Característica Clave",
    "Reconnaissance Equipment": "Equipo de Reconocimiento",
    "Electromagnetic Equipment": "Equipo Electromagnético",
    "Navigation System": "Sistema de Navegación",
    "Navigation & Communication": "Navegación y Comunicación",
    "Navigation &amp; Communication": "Navegación y Comunicación",
    "Anti-jamming Capability": "Capacidad Anti-interferencia",
    "Deployment Type": "Tipo de Despliegue",
    "Deployment Design": "Diseño de Despliegue",
    "Safety Function": "Función de Seguridad",
    "Maximum Coverage": "Cobertura Máxima",
    "Security Function": "Función de Seguridad",
    "Logistics & Support Delivery": "Entrega de Apoyo Logístico",
    "Logistics &amp; Support Delivery": "Entrega de Apoyo Logístico",
    "Suspension System": "Sistema de Suspensión",
    "Frame Dimensions": "Dimensiones del Chasis",
    "Maximum Load Capacity": "Capacidad de Carga Máxima",
    "Positioning Method": "Método de Posicionamiento",
    "Driving Speed": "Velocidad de Conducción",
    "Climbing Angle": "Ángulo de Escalada",
    "Power Output": "Potencia de Salida",
    "Power Type": "Tipo de Potencia",
    "Operating Temperature Range": "Rango de Temperatura de Operación",
    "Continuous Endurance": "Autonomía Continua",
    "Core Maneuverability": "Maniobrabilidad Principal",
    "Maximum Image Transmission Range": "Alcance Máximo de Transmisión de Imagen",
    "Max Data Transmission Distance": "Distancia Máx de Transmisión de Datos",
    "Movement Speed": "Velocidad de Movimiento",
    "Net Weight": "Peso Neto",
    "Minimum Take-Off Taxi Distance": "Distancia Mínima de Rodaje para Despegue",
}

def translate_text(text):
    """翻译文本，应用专业术语"""
    if not text:
        return text
    
    result = text
    
    # 按长度排序，长的先替换（避免部分匹配）
    sorted_terms = sorted(term_translations.items(), key=lambda x: len(x[0]), reverse=True)
    
    # 应用术语翻译
    for en, es in sorted_terms:
        # 使用正则表达式进行大小写不敏感的替换
        result = re.sub(re.escape(en), es, result, flags=re.IGNORECASE)
    
    return result

def translate_specs(specs):
    """翻译规格参数"""
    translated_specs = {}
    
    for key, value in specs.items():
        # 翻译键名
        translated_key = spec_key_translations.get(key, key)
        
        # 翻译值
        translated_value = translate_text(value)
        
        translated_specs[translated_key] = translated_value
    
    return translated_specs

# 读取英文版本
with open('d:/Project/seekdrn/docs/products_en.json', 'r', encoding='utf-8') as f:
    products = json.load(f)

# 完整翻译每个产品
translated_products = []

for product in products:
    translated = {
        "name": product["name"],
        "category": product["category"],
        "slug": product["slug"],
        "url": product["url"],
        "fullTitle": translate_text(product["fullTitle"]),
        "description": translate_text(product["description"]),
        "advantages": translate_text(product["advantages"]),
        "capabilities": translate_text(product["capabilities"]) if product["capabilities"] else "",
        "applications": translate_text(product["applications"]),
        "specs": translate_specs(product["specs"]),
        "specCount": product["specCount"],
        "hasChinese": product["hasChinese"]
    }
    translated_products.append(translated)

# 保存西班牙语版本
with open('d:/Project/seekdrn/docs/products_es.json', 'w', encoding='utf-8') as f:
    json.dump(translated_products, f, ensure_ascii=False, indent=2)

print(f"翻译完成！共翻译 {len(translated_products)} 个产品")
